window.NHA_TRANG_CHECKLIST = [
  {
    id: "priority",
    icon: "✦",
    title: "오늘 먼저 할 일",
    description: "출발 전에 가장 먼저 끝내야 할 핵심",
    items: [
      ["priority-passport", "여권 유효기간과 훼손 여부 확인", true],
      ["priority-flight", "왕복 항공권·수하물 규정 확인", true],
      ["priority-hotel", "전체 숙소 예약과 날짜 확인", true],
      ["priority-insurance", "여행자보험 가입", true],
      ["priority-esim", "eSIM 또는 유심 결정", true],
      ["priority-cards", "해외결제 카드 2장 준비", true],
      ["priority-arrival", "입국 전 필요한 신고 여부 재확인", true],
    ],
  },
  {
    id: "entry",
    icon: "▣",
    title: "여권 · 입국",
    description: "공항에서 당황하지 않도록 서류 준비",
    items: [
      ["entry-passport-expiry", "입국일 기준 여권 잔여 유효기간 확인", true],
      ["entry-passport-copy", "여권 사본을 휴대폰과 클라우드에 저장", true],
      ["entry-name", "항공권 영문 이름과 여권 이름 일치 확인", true],
      ["entry-return-ticket", "귀국 항공권 예약 내역 저장", true],
      ["entry-hotel-address", "첫 숙소 영문명·주소·전화번호 저장", true],
      ["entry-form", "출발 1~3일 전 최신 입국 절차 확인", true],
      ["entry-form-shot", "입국 사전신고를 했다면 완료 화면 캡처", false],
      ["entry-visa", "내 여권·체류기간에 맞는 비자 필요 여부 확인", true],
    ],
  },
  {
    id: "flight-hotel",
    icon: "⌁",
    title: "항공 · 숙소",
    description: "예약 조건과 이동 시간을 한 번 더 확인",
    items: [
      ["flight-number", "항공편명·출발 터미널·도착 시간 확인", true],
      ["flight-baggage", "위탁·기내 수하물 허용량 확인", true],
      ["flight-battery", "보조배터리 기내반입 규정 확인", true],
      ["flight-checkin", "온라인 체크인 가능 시간 알림 설정", false],
      ["hotel-dates", "체크인·체크아웃 날짜 확인", true],
      ["hotel-voucher", "숙소 예약번호와 바우처 저장", true],
      ["hotel-request", "늦은 도착·조식·침대 타입 요청 확인", false],
      ["hotel-registration", "개인 숙소라면 외국인 숙박 신고 여부 문의", false],
    ],
  },
  {
    id: "insurance",
    icon: "+",
    title: "여행자보험",
    description: "보장 범위와 긴급 연락처까지 준비",
    items: [
      ["insurance-medical", "해외 상해·질병 의료비 보장 확인", true],
      ["insurance-evacuation", "응급의료 이송·본국 송환 보장 확인", true],
      ["insurance-liability", "배상책임 보장 확인", false],
      ["insurance-baggage", "휴대품 도난·파손 조건과 자기부담금 확인", false],
      ["insurance-delay", "항공·수하물 지연 보장 확인", false],
      ["insurance-water", "스노클링 등 해양 액티비티 보장 확인", true],
      ["insurance-period", "집 출발부터 귀가까지 보험기간 설정", true],
      ["insurance-pdf", "보험증권 PDF와 긴급전화번호 저장", true],
    ],
  },
  {
    id: "connectivity",
    icon: "⌁",
    title: "통신 · 필수 앱",
    description: "도착 직후 바로 연결되고 이동할 수 있게",
    items: [
      ["connect-esim", "베트남 데이터 eSIM 또는 유심 구매", true],
      ["connect-install", "출국 전 eSIM 설치 방법 확인", true],
      ["connect-roaming", "현지에서 한국 회선 데이터로밍 끄기", true],
      ["app-grab", "Grab 설치·결제수단 등록", true],
      ["app-maps", "Google Maps와 주요 장소 저장", true],
      ["app-translate", "Google Translate·베트남어 오프라인팩 설치", false],
      ["app-airline", "이용 항공사 앱 설치", false],
      ["app-safety", "해외안전여행 앱 설치·일정 등록", false],
    ],
  },
  {
    id: "money",
    icon: "₫",
    title: "결제 · 환전",
    description: "카드와 현금을 나눠 안전하게 보관",
    items: [
      ["money-card-a", "해외결제 가능한 카드 A 준비", true],
      ["money-card-b", "다른 카드사 카드 B 준비", true],
      ["money-block", "카드 해외결제 차단 여부 확인", true],
      ["money-pin", "카드 비밀번호 확인", true],
      ["money-alert", "해외결제 알림 켜기", false],
      ["money-vnd", "베트남 동(VND) 현금 준비", true],
      ["money-emergency", "비상용 원화 또는 달러 준비", false],
      ["money-separate", "카드 두 장을 서로 다른 곳에 보관", true],
    ],
  },
  {
    id: "transport",
    icon: "➜",
    title: "공항 · 현지 이동",
    description: "깜란공항에서 숙소까지 매끄럽게",
    items: [
      ["transport-arrival", "공항 도착 후 이동수단 결정", true],
      ["transport-pickup", "늦은 도착이면 픽업 또는 예약차량 확정", false],
      ["transport-price", "공항 이동 가격·미팅 장소 확인", false],
      ["transport-hotel-message", "숙소에 공항 픽업 가능 여부 문의", false],
      ["transport-grab", "Grab 호출 시 차량번호 확인 습관 기억", true],
      ["transport-return", "마지막 날 공항 샌딩 시간 결정", true],
      ["transport-buffer", "국제선 공항 도착 여유시간 계산", true],
      ["transport-bike", "오토바이 대신 안전한 이동수단 사용", false],
    ],
  },
  {
    id: "bookings",
    icon: "◇",
    title: "투어 · 예약",
    description: "인기 일정과 취소 조건을 미리 확인",
    items: [
      ["booking-vinwonders", "VinWonders 방문·예매 여부 결정", false],
      ["booking-island", "섬투어·스노클링 예약", false],
      ["booking-weather", "해양투어 우천 취소·환불 규정 확인", true],
      ["booking-mud", "머드바스 예약 여부 결정", false],
      ["booking-massage", "인기 마사지 예약", false],
      ["booking-nail", "네일 예약", false],
      ["booking-food", "가고 싶은 식당 지도에 저장", false],
      ["booking-voucher", "모든 예약 QR·바우처 오프라인 저장", true],
    ],
  },
  {
    id: "documents",
    icon: "▤",
    title: "문서 · 백업",
    description: "인터넷이 없어도 열 수 있게 한 폴더에",
    items: [
      ["doc-folder", "휴대폰에 ‘나트랑 여행’ 폴더 만들기", true],
      ["doc-passport", "여권 사본 저장", true],
      ["doc-flight", "왕복 항공권 저장", true],
      ["doc-hotel", "숙소 예약확인서 저장", true],
      ["doc-insurance", "여행자보험 증권 저장", true],
      ["doc-transfer", "공항 픽업·샌딩 예약 저장", false],
      ["doc-tours", "투어·입장권 바우처 저장", false],
      ["doc-cloud", "같은 파일을 클라우드에도 백업", true],
      ["doc-family", "가족에게 항공편·숙소 정보 공유", false],
    ],
  },
  {
    id: "clothes",
    icon: "☼",
    title: "의류 · 날씨",
    description: "더위와 강한 냉방, 소나기에 대비",
    items: [
      ["clothes-weather", "출발 직전 나트랑 날씨 재확인", true],
      ["clothes-tops", "반팔 상의", true],
      ["clothes-bottoms", "반바지·얇은 하의", true],
      ["clothes-underwear", "속옷·양말", true],
      ["clothes-long", "냉방 대비 얇은 긴팔 1개", false],
      ["clothes-shoes", "운동화와 샌들·슬리퍼", false],
      ["clothes-rain", "접이식 우산 또는 얇은 우의", false],
      ["clothes-sun", "모자·선글라스", true],
    ],
  },
  {
    id: "health",
    icon: "✚",
    title: "건강 · 위생",
    description: "상비약과 모기·햇빛 대비",
    items: [
      ["health-prescription", "평소 복용약과 여유분", true],
      ["health-painkiller", "진통·해열제", false],
      ["health-digestion", "소화제·지사제", false],
      ["health-motion", "멀미약", false],
      ["health-firstaid", "밴드·상처 소독용품", false],
      ["health-repellent", "모기기피제", true],
      ["health-bites", "벌레물림용 제품", false],
      ["health-sunscreen", "선크림", true],
      ["health-hydration", "전해질·수분 보충용 제품", false],
      ["health-sanitizer", "손 소독제·물티슈", false],
    ],
  },
  {
    id: "electronics",
    icon: "⌁",
    title: "전자기기",
    description: "충전과 방수까지 빠짐없이",
    items: [
      ["device-phone", "휴대폰", true],
      ["device-charger", "충전기와 충전 케이블", true],
      ["device-battery", "보조배터리", true],
      ["device-multi", "멀티충전기 또는 여행용 어댑터", false],
      ["device-earphones", "이어폰", false],
      ["device-watch", "스마트워치 충전기", false],
      ["device-camera", "카메라·메모리카드·충전기", false],
      ["device-waterproof", "방수 휴대폰 파우치", false],
    ],
  },
  {
    id: "water",
    icon: "≈",
    title: "물놀이 · 바다",
    description: "섬투어와 리조트 수영 준비",
    items: [
      ["water-swimsuit", "수영복 1~2벌", false],
      ["water-rashguard", "래시가드", false],
      ["water-shoes", "아쿠아슈즈", false],
      ["water-drybag", "작은 방수백·방수팩", false],
      ["water-change", "여벌 옷과 작은 수건", false],
      ["water-sunscreen", "워터프루프 선크림", false],
      ["water-lifejacket", "투어 시 구명조끼 착용", true],
      ["water-safety", "음주 후 수영·스노클링하지 않기", true],
    ],
  },
  {
    id: "departure-return",
    icon: "✓",
    title: "출국 당일 · 귀국",
    description: "문을 나서기 전 마지막 확인",
    items: [
      ["day-passport", "여권", true],
      ["day-wallet", "지갑·카드 2장·현금", true],
      ["day-phone", "휴대폰·충전기·보조배터리", true],
      ["day-ticket", "항공권·숙소 주소", true],
      ["day-insurance", "보험증권·긴급연락처", true],
      ["day-esim", "eSIM 설치 상태 확인", true],
      ["day-baggage", "수하물 무게와 금지물품 확인", true],
      ["return-duty", "귀국 전 면세한도·반입물품 확인", false],
      ["return-purchases", "신고할 구매물품이 있는지 확인", false],
      ["emergency-numbers", "영사안전콜센터 번호 저장", true],
    ],
  },
].map((category) => ({
  ...category,
  items: category.items.map(([id, title, required]) => ({ id, title, required })),
}));

